name: Deploy Backend

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.PASSWD }}
          script: |
            cd ~/chauchaapp-backend/chauchaapp-backend
            git fetch origin
            git checkout develop
            git pull --ff-only origin develop
            docker compose --profile production down
            docker compose --profile production up -d --build
