name: Deploy Backend

on:
  push:
    branches:
      - feature/CI-CD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Deploy to Ubuntu Server
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

          script: |
            cd /home/shade/apps/backend/chauchaapp-backend

            git fetch origin

            git checkout feature/CI-CD

            git pull --ff-only origin feature/CI-CD

            docker compose --profile production down

            docker compose --profile production up -d --build
